channels:
  - conda-forge
  - apt-tools
dependencies:
  - python
  - jupyterlab
  - ipywidgets
  - ipython
  - paraprobe
  - pyiron_base
  - numpy
  - matplotlib
  - pytest
  - pandas
  - numba
  - h5py
  - scikit-learn
  - tqdm
  - pyevtk
  - ipywidgets
  - pyyaml
  - ipyvtklink
  - pyvista
  - panel
  - jupyterlab-h5web
  - pip:
    - compositionspace
    
